### ISSUE TITLE
Facebook Notification Installation

### ISSUE THREAD

**Issue by christophrumpel** [laravel-notification-channels/new-channels#10]
Hey, I wanted to test the Facebook notifications but the package is not yet on Packagist.
Should it work if I just download it and throw it in the vendors folder like `vendor/<vendor name/<package name>`?

Because I get a
````
Class 'NotificationChannels\Facebook\FacebookServiceProvider' not found
````

Cheers

**Comment by themsaid** [comment]
@christophrumpel I'm submitting it right now :)

**Comment by themsaid** [comment]
Done: https://packagist.org/packages/laravel-notification-channels/facebook
