### ISSUE TITLE
[Proposal] Add Authors to Organization!

### ISSUE THREAD

**Issue by irazasyed** [laravel-notification-channels/new-channels#15]
How about adding channel authors to the organization?

I have some valid points on why I think you should add and would be good to do so.

- When you add the person and list them public, the organization's logo starts showing up in collaborator's profile under "Organizations" they're part of.
- Having the organization under author's profile not only brings a sense of pride but also benefits in several ways, I'll mention a few below.
- It cross-promotes the organization as well as the author & helps in discovery from across all the authors' profiles and similarly, people exploring organization can get to know all the collaborators that are part of this organization. So it's a win-win for both.
- It's validation of author's credentials of work experience, contributions, and valuable to showcase. This would especially be useful for freelancers, developers that apply for a job and others.
- It's a community organization, So having everyone part of the team totally makes sense, unless there's a different plan that we should know.
- Adding people to the organization as a collaborator doesn't give full access or access to any other repositories by default. So you can be rest assured, there's no one poking around and potentially causing damage to any repo (If that's the concern?).
- It's gonna motivate more people to contribute to this project because they so want to be part of this organization. It's like those achievement badges you eagerly want in your profile. So the more people that come up to contribute, the better the project gets automatically.
- Even @thephpleague does it. Refer [this](https://github.com/orgs/thephpleague/people).

The only access a collaborator would get is to be able to create a new repo under the organization by default which can also be turned off from the [settings](https://github.com/organizations/laravel-notification-channels/settings/member_privileges) page. So this would give no access to anything other than just listing them under People page as well as showing a logo in profile. Although, We can let the repository creation privilege left. Because a collaborator would only wanna create a new one if they're working on a new channel but otherwise no one would create and worst case scenario, if they do abuse this access, you can revoke their membership.

Hopefully, your guys will consider my proposal. Let me know your thoughts. Thanks!

cc @freekmurze @themsaid @mpociot

**Comment by freekmurze** [comment]
Hi thanks for you suggestion. I highly appreciated that you listed all those point.

We'll discuss this internally and get back to you!

**Comment by freekmurze** [comment]
We agree with your points and will start adding all authors as members of the organisation soon.

Authors will only be able to write to their own repo.

Thank you again for suggesting this to us.

**Comment by irazasyed** [comment]
Thanks for accepting my proposal and taking swift decision. 

I'm glad you guys considered it. Highly appreciated :)

Sounds good about the write access to their own repo, that's how it should be. Perfect 👍 

Thank you!
